# Random Numbers in NumPy

## What is Random Number?

Random number does NOT mean a different number every time. Random means something that can not be predicted logically.

## Pseudo Random and True Random

Computers work on programs, and programs are definitive set of instructions. So it means there must be some algorithm to generate a random number as well.

If there is a program to generate random number it can be predicted, thus it is not truly random.

Random numbers generated through a generation algorithm are called pseudo random.

Can we make truly random numbers?

Yes. In order to generate a truly random number on our computers we need to get the random data from some outside source. This outside source is generally our keystrokes, mouse movements, data on network etc.

We do not need truly random numbers, unless its related to security (e.g. encryption keys) or the basis of application is the randomness (e.g. Digital roulette wheels).

In this tutorial we will be using pseudo random numbers.

## Generate Random Numbers

NumPy offers the random module to work with random numbers.

In [16]:
from numpy import random

In [17]:
# Generate a random integer from 0 to 100
x = random.randint(100)
print(x)

64


## Generate Random Float

The random module's rand() method returns a random float between 0 and 1.

In [18]:
rf = random.rand()
print(rf)

0.11201053441505915


## Generate Random Array

In NumPy we work with arrays, and you can use the two methods from the above examples to make random arrays.

### Integers

The randint() method takes a size parameter where you can specify the shape of an array.

In [19]:
# Generate a 1-D array containing 5 random integers from 0 to 100
ra = random.randint(100, size=(5))
print(ra)

[ 0 13 91 39 81]


In [20]:
# Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100
ra1 = random.randint(100, size=(3, 5))
print(ra1)

[[43 66 86 59 15]
 [16 94 87 51 28]
 [86 62 19 89 62]]


### Floats

The rand() method also allows you to specify the shape of the array.

In [21]:
# Generate a 1-D array containing 5 random floats
rf1 = random.rand(5)
print(rf1)

[0.1742757  0.94285588 0.8002156  0.52659532 0.8291402 ]


In [22]:
# Gebearate a 2-D array with 3 rows, each containing 5 random numbers

rf2 = random.rand(3,5)
print(rf2)

[[0.34224455 0.17097734 0.59350151 0.50728458 0.41480004]
 [0.31069449 0.44389215 0.33306722 0.27890919 0.13384345]
 [0.18497854 0.79760745 0.64799911 0.6388544  0.68736145]]


## Generate Random Number From Array

The choice() method allows you to generate a random value based on an array of values.

The choice() method takes an array as a parameter and randomly returns one of the values.

In [23]:
# Return one of the values in an array

c1 = random.choice([2, 3, 6, 7, 4, 0, 8])
print(c1)

6


The choice() method also allows you to return an array of values.

Add a size parameter to specify the shape of the array.

In [24]:
# Generate a 2-D array that consists of the value in the array parameter (3, 5, 7, and 9)

c2 = random.choice([3, 5, 7, 9], size=(3, 5))
print(c2)

[[7 7 5 9 9]
 [9 9 5 7 9]
 [9 5 5 5 9]]
