# Creating Arrays with NumPy

In [41]:
import numpy as np

NumPy is used to work with arrays. The array object in NumPy is called ndarray.
We can create a NumPy ndarray object by using the array() function.

In [42]:
arr = np.array([1, 5, 9, 3, 6, 4])

In [43]:
print(arr)

[1 5 9 3 6 4]


In [44]:
print(type(arr))

<class 'numpy.ndarray'>


To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray

In [45]:
arr2 =  np.array((1, 5, 7, 6, 4))

In [46]:
print(arr2)

[1 5 7 6 4]


## Dimensions in Arrays

A dimension in arrays is one level of array depth (nested arrays).

### 0-D Arrays

0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [47]:
scalar = np.array(63)

In [48]:
print(scalar)

63


### 1-D Arrays

An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.

In [49]:
one_d_array = np.array([7, 6, 3, 8, 4, 2])

In [50]:
print(one_d_array)

[7 6 3 8 4 2]


### 2-D Arrays

An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

In [51]:
two_d_array = np.array([[1, 4, 7], [9, 6, 3]])

In [52]:
print(two_d_array)

[[1 4 7]
 [9 6 3]]


### 3-D Arrays

An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

In [53]:
three_d_array = np.array([[[1,5,9], [5,3,6]],[[8,5,3],[3,4,9]]])

In [54]:
print(three_d_array)

[[[1 5 9]
  [5 3 6]]

 [[8 5 3]
  [3 4 9]]]


## Checking the Number of Dimensions

NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [55]:
print(scalar.ndim)

0


In [56]:
print(one_d_array.ndim)

1


In [57]:
print(two_d_array.ndim)

2


In [58]:
print(three_d_array.ndim)

3


## Higher Dimensional Arrays

An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndmin argument.

In [59]:
test_arr = np.array([1, 2, 3, 4, 5], ndmin=5)

In [60]:
print(test_arr)

[[[[[1 2 3 4 5]]]]]


In [61]:
print(f"Number of dimensions: {test_arr.ndim}")

Number of dimensions: 5
