# NumPy Array Slicing

In [19]:
import numpy as np

## Slicing Arrays

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

Note: The result includes the start index, but excludes the end index.

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [20]:
arr1 = np.array([52, 87, 347, 62, 74, 96, 23, 14, 48])

In [21]:
# Slice elements from index 1 to index 5
print(arr1[1:5])

[ 87 347  62  74]


In [22]:
# Slice elements from index 4 to the end of the array
print(arr1[4:])

[74 96 23 14 48]


In [23]:
# Slice elements from the beginning to index 4 (not included)
print(arr1[:4])

[ 52  87 347  62]


In [24]:
# Slice from the index 3 from the end to index 1 from the end
print(arr1[-3:-1])

[23 14]


In [25]:
# Return every other element from index 1 to index 5
print(arr1[1:5:2])

[87 62]


In [26]:
# Return every other element from the entire array
print(arr1[::2])

[ 52 347  74  23  48]


## Slicing 2-D Arrays

In [27]:
arr2 = np.array([[9,71,35,21,65,12], [87,45,12,23,56,89]])

In [28]:
# From the second element, slice elements from index 1 to index 4 (not included)
print(arr2[1, 1:4])

[45 12 23]


In [29]:
# From both elements, return index 2
print(arr2[0:2, 2])

[35 12]


In [30]:
# From both elements, slice index 1 to index 4 (not included), this will return a 2-D array
print(arr2[0:2,1:4])

[[71 35 21]
 [45 12 23]]
