# NumPy Array Interating

In [21]:
import numpy as np

## Iterating Arrays

Iterating means going through elements one by one.

As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

If we iterate on a 1-D array it will go through each element one by one.

In [22]:
arr1 = np.array([1,5,9,7,3,6,8,4,2])

In [23]:
for i in arr1:
    print(i)

1
5
9
7
3
6
8
4
2


## Iterating 2-D Arrays

In a 2-D array it will go through all the rows.

In [24]:
arr2 = np.array([[1,2,3], [4,5,6]])

In [25]:
for i in arr2:
    print(i)

[1 2 3]
[4 5 6]


To return the actual values, the scalars, we have to iterate the arrays in each dimension.

In [26]:
for x in arr2:
    for y in x:
        print(y)

1
2
3
4
5
6


## Iterating 3-D Arrays

In [27]:
arr3 = np.array([[[1,2,3], [7,8,9]], [[5,4,6], [9,5,1]]])
print(arr3)

[[[1 2 3]
  [7 8 9]]

 [[5 4 6]
  [9 5 1]]]


In [28]:
for i in arr3:
    print(i)

[[1 2 3]
 [7 8 9]]
[[5 4 6]
 [9 5 1]]


To return the actual values, the scalars, we have to iterate the arrays in each dimension.

In [29]:
for i in arr3:
    for j in i:
        for k in j:
            print(k)

1
2
3
7
8
9
5
4
6
9
5
1


## Iterating Arrays Using nditer()

The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration.

### Iterating on Each Scalar Element

In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

In [30]:
arr4 = np.array([[[9,5], [3,2]], [[7,3], [8, 6]]])
print(arr4)

[[[9 5]
  [3 2]]

 [[7 3]
  [8 6]]]


In [31]:
for x in np.nditer(arr4):
    print(x)

9
5
3
2
7
3
8
6


## Iterating Array with Different Data Types

We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.

NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

In [32]:
arr5 = np.array([9,5,4,6,3])
print(arr5)

[9 5 4 6 3]


In [33]:
for x in np.nditer(arr5, flags=['buffered'], op_dtypes=['S']):
    print(x)

b'9'
b'5'
b'4'
b'6'
b'3'


## Iterating with Different Step Size

We can use filtering and followed by iteration

In [34]:
# Iterate through every scalar element of the 2D array skipping 1 element
arr6 = np.array([[4,5,6,7], [8,6,1,4]])
print(arr6)

[[4 5 6 7]
 [8 6 1 4]]


In [35]:
for i in np.nditer(arr6[:, ::2]):
    print(i)

4
6
8
1


## Enumerated Iteration Using ndenumerate()

Enumeration means mentioning sequence number of somethings one by one.

Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

In [36]:
arr7 = np.array([98, 45, 75 ,62, 21, 35, 58])

In [37]:
for index, x in np.ndenumerate(arr7):
    print(f"{index} -> {x}")

(0,) -> 98
(1,) -> 45
(2,) -> 75
(3,) -> 62
(4,) -> 21
(5,) -> 35
(6,) -> 58


In [38]:
# Enumerate on 2-D array

arr8 = np.array([[7,5,4,8], [3,1,4,9]])

In [39]:
for idx, i in np.ndenumerate(arr8):
    print(f"{idx} -> {i}")

(0, 0) -> 7
(0, 1) -> 5
(0, 2) -> 4
(0, 3) -> 8
(1, 0) -> 3
(1, 1) -> 1
(1, 2) -> 4
(1, 3) -> 9
