# NumPy Array Reshaping

In [17]:
import numpy as np

## Reshaping Arrays

Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

## Resgape from 1-D to 2-D

In [18]:
#Convert the following 1-D array with 12 elements into a 2-D array. The outermost dimension will have 4 arrays, each with 3 elements

arr1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [19]:
print(arr1.shape)

(12,)


In [20]:
new_arr1 = arr1.reshape(4, 3)
print(new_arr1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## Reshape from 1-D to 3-D

In [21]:
#Convert the following 1-D array with 12 elements into a 3-D array. The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements

arr2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [22]:
print(arr2.shape)

(12,)


In [23]:
new_arr2 = arr2.reshape(2, 3, 2)
print(new_arr2)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


## Unknown Dimension

You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [24]:
# Convert 1D array with 8 elements to 3D array with 2x2 elements

arr3 = np.array([1,2,3,4,5,6,7,8])
print(arr3)

[1 2 3 4 5 6 7 8]


In [25]:
new_arr3 = arr3.reshape(2,2,-1)
print(new_arr3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [26]:
n4 = arr2.reshape(2,2, -1)
print(n4)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## Flattening the Arrays

Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

There are a lot of functions for changing the shapes of arrays in numpy flatten, ravel and also for rearranging the elements rot90, flip, fliplr, flipud etc.

In [27]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [28]:
narr = arr.reshape(-1)
print(narr)

[1 2 3 4 5 6]


In [29]:
nr1 = arr.flatten()
print(nr1)

[1 2 3 4 5 6]


In [30]:
nr2 = arr.ravel()
print(nr2)

[1 2 3 4 5 6]
