# NumPy Data Types

In [1]:
import numpy as np

## Data types in Python

By default Python have these data types:

strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"

integer - used to represent integer numbers. e.g. -1, -2, -3

float - used to represent real numbers. e.g. 1.2, 42.42

boolean - used to represent True or False.

complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

## Data Types in NumPy

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer

b - boolean

u - unsigned integer

f - float

c - complex float

m - timedelta

M - datetime

O - object

S - string

U - unicode string

V - fixed chunk of memory for other type ( void )

## Checking the Data Type of an Array

The NumPy array object has a property called dtype that returns the data type of the array

In [2]:
arr1 = np.array([1,2,3,4,5,6,7])

In [3]:
print(arr1.dtype)

int32


In [4]:
arr2 = np.array([12, 134, 67, 985, 5564554])

In [5]:
print(arr2.dtype)

int32


In [6]:
arr3 = np.array([1.023, 0.00235, 6.35, 4])

In [7]:
print(arr3.dtype)

float64


In [8]:
arr4 = np.array(['apple', 'orange', 'banana', 'cherry'])

In [9]:
print(arr4.dtype)

<U6


## Creating Arrays with a defined Data Type

We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements

In [10]:
# Create an array with data type string
arr5 = np.array([5,9,4,7], dtype='S')

In [11]:
print(arr5)

[b'5' b'9' b'4' b'7']


In [12]:
print(arr5.dtype)

|S1


In [13]:
# Create an array with data type 4 bytes integer
arr6 = np.array([1,2,24,6], dtype='i4')

In [14]:
print(arr6)

[ 1  2 24  6]


In [15]:
print(arr6.dtype)

int32


## Converting Data Type on Existing Arrays

The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [16]:
arr7 = np.array([1.1, 2.2, 5.6])

In [17]:
narr7 = arr7.astype('i')

In [18]:
print(narr7)

[1 2 5]


In [19]:
print(narr7.dtype)

int32


In [20]:
narr8 = arr7.astype(int)

In [21]:
print(narr8)

[1 2 5]


In [22]:
print(narr8.dtype)

int32


In [23]:
# Change data type from integer to boolean
arr9 = np.array([1,5,0,6,0,2,1,0,8])
nar = arr9.astype(bool)

In [24]:
print(nar)

[ True  True False  True False  True  True False  True]


In [25]:
print(nar.dtype)

bool
