# NumPy Array Copy vs View

In [19]:
import numpy as np

## The difference between Copy and View

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

## Copy

In [20]:
# Make a copy, change the original array, and display both arrays
arr1 = np.array([1,4,9,5,6,7])
x = arr1.copy()

In [21]:
arr1[0] = 34

In [22]:
print(arr1)

[34  4  9  5  6  7]


In [23]:
print(x)

[1 4 9 5 6 7]


## View

In [24]:
arr2 = np.array([78, 95, 35, 46, 47])
y = arr2.view()

In [25]:
arr2[0] = 9

In [26]:
print(arr2)

[ 9 95 35 46 47]


In [27]:
print(y)

[ 9 95 35 46 47]


In [28]:
y[0] = 42

In [29]:
print(y)

[42 95 35 46 47]


In [30]:
print(arr2)

[42 95 35 46 47]


## Check If the Array Owns its Data

As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

Every NumPy array has the attribute base that returns None if the array owns the data.

Otherwise, the base  attribute refers to the original object.

In [31]:
# Print the value of the base attribute to check if an array owns it's data or not
arr = np.array([8, 7, 6, 4, 2])
c = arr.copy()
v = arr.view()

In [32]:
print(arr.base)

None


In [33]:
print(c.base)

None


In [34]:
print(v.base)

[8 7 6 4 2]
