# NumPy Joining Arrays

In [1]:
import numpy as np

Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [2]:
arr1 = np.array([4,5,6])
arr2 = np.array([9,8,7])

In [3]:
arrj = np.concatenate((arr1, arr2))

In [4]:
print(arrj)

[4 5 6 9 8 7]


In [6]:
# Join two 2-D arrays along rows (axis=1)

arr3 = np.array([[1,2], [5,8]])
arr4 = np.array([[8,0], [7,4]])

In [12]:
arrj2 = np.concatenate((arr3, arr4), axis=1)

In [13]:
print(arrj2)

[[1 2 8 0]
 [5 8 7 4]]


## Joining Arrays Using Stack Functions

Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [14]:
arr5 = np.array([5,4,7])
arr6 = np.array([7,8,3])

In [15]:
arrj3 = np.stack((arr5, arr6))

In [16]:
print(arrj3)

[[5 4 7]
 [7 8 3]]


In [17]:
arrj4 = np.stack((arr5, arr6), axis=1)

In [18]:
print(arrj4)

[[5 7]
 [4 8]
 [7 3]]


## Stacking Along Rows

NumPy provides a helper function: hstack() to stack along rows.

In [19]:
arr7 = np.array([11, 22,33])
arr8 = np.array([44, 55, 66])

In [21]:
arrh = np.hstack((arr7, arr8))

In [22]:
print(arrh)

[11 22 33 44 55 66]


## Stacking Along Columns

NumPy provides a helper function: vstack()  to stack along columns.

In [23]:
arrv = np.vstack((arr7, arr8))

In [24]:
print(arrv)

[[11 22 33]
 [44 55 66]]


## Stacking Along Height (depth)

NumPy provides a helper function: dstack() to stack along height, which is the same as depth.

In [25]:
arrd = np.dstack((arr7, arr8))

In [26]:
print(arrd)

[[[11 44]
  [22 55]
  [33 66]]]
