# NumPy Sorting Arrays

In [1]:
import numpy as np

Sorting means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

The NumPy ndarray object has a function called sort(), that will sort a specified array.

Note: This method returns a copy of the array, leaving the original array unchanged.

In [3]:
arr1 = np.array([58, 0, 445, 78, 32, 12, 14, 58, 86, 54])

In [4]:
print(np.sort(arr1))

[  0  12  14  32  54  58  58  78  86 445]


In [5]:
arr2 = np.array(['banana', 'orange', 'apple', 'cherry'])

In [6]:
print(np.sort(arr2))

['apple' 'banana' 'cherry' 'orange']


In [7]:
# Sort a Boolean Array

arr3 = np.array([True, False, True, True, False, False, True])
print(np.sort(arr3))

[False False False  True  True  True  True]


## Sorting a 2-D Array

If you use the sort() method on a 2-D array, both arrays will be sorted

In [8]:
arr4 = np.array([[2, 8, 4], [7, 6, 1]])

In [9]:
print(np.sort(arr4))

[[2 4 8]
 [1 6 7]]
