# NumPy Searching Arrays

In [26]:
import numpy as np

You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

In [27]:
arr1 = np.array([65, 56, 84, 58, 75, 14, 53, 14, 55, 34, 24, 14, 25])

In [28]:
x1 = np.where(arr1 == 14)

In [29]:
print(x1)

(array([ 5,  7, 11], dtype=int64),)


In [30]:
# Find the indexes where the values are even

ev = np.where(arr1%2 == 0)

In [31]:
print(ev)

(array([ 1,  2,  3,  5,  7,  9, 10, 11], dtype=int64),)


## Search Sorted

There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

The searchsorted() method is assumed to be used on sorted arrays.

In [32]:
# Find the indexes where the value 7 should be inserted

arr2 = np.array([5,6,7,8,10])

In [33]:
x2 = np.searchsorted(arr2, 7)

In [34]:
print(x2)

2


Example explained: The number 7 should be inserted on index 2 to remain the sort order.

The method starts the search from the left and returns the first index where the number 7 is no longer larger than the next value.

### Search From the Right Side

By default the left most index is returned, but we can give side='right' to return the right most index instead.

In [35]:
r2 = np.searchsorted(arr2, 7, side='right')

In [36]:
print(r2)

3


Example explained: The number 7 should be inserted on index 3 to remain the sort order.

The method starts the search from the right and returns the first index where the number 7 is no longer less than the next value.

### Multiple Values

To search for more than one value, use an array with the specified values.

In [37]:
# Find the indexes where the values 2, 4, and 6 should be inserted

arr3 = np.array([1, 3, 5,  7])

In [38]:
x = np.searchsorted(arr3, [2,4,6])

In [39]:
print(x)

[1 2 3]


The return value is an array: [1 2 3] containing the three indexes where 2, 4, 6 would be inserted in the original array to maintain the order.