# NumPy Filter Array

In [17]:
import numpy as np

Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

A boolean index list is a list of booleans corresponding to indexes in the array.

If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

In [18]:
# Create an array from the elements on index 0 and 2
arr1 = np.array([11,12,13,14])

In [19]:
ind1 = [True, False, True, False]

In [20]:
narr1 = arr1[ind1]

In [21]:
print(narr1)

[11 13]


## Creating the Filter Array

In [22]:
# Create a filter array that will return only values higher than 42

arr2 = np.array([11, 54, 86, 42, 43, 41, 54, 55, 63, 12])

# Create an empty list
filter_arr = []

# Go through each element in arr2
for e in arr2:
    if e > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

narr = arr2[filter_arr]

In [23]:
print(filter_arr)

[False, True, True, False, True, False, True, True, True, False]


In [24]:
print(narr)

[54 86 43 54 55 63]


## Creating Filter Directly From Array

The above example is quite a common task in NumPy and NumPy provides a nice way to tackle it.

We can directly substitute the array instead of the iterable variable in our condition and it will work just as we expect it to.

In [25]:
# Create a filter array that will return only values higher than 42

arr3 = np.array([11, 54, 86, 42, 43, 41, 54, 55, 63, 12])

flt = arr3 > 42

narr3 = arr3[flt]

In [26]:
print(flt)

[False  True  True False  True False  True  True  True False]


In [27]:
print(narr3)

[54 86 43 54 55 63]


In [28]:
# Create a filter array that will return only even elements from the original array

arr4 = np.array([1, 2, 3, 2, 4, 5, 6, 8, 10, 12, 22, 23, 32, 13, 12])

flt4 = arr4%2 == 0

narr4 = arr4[flt4]

In [29]:
print(flt4)

[False  True False  True  True False  True  True  True  True  True False
  True False  True]


In [30]:
print(narr4)

[ 2  2  4  6  8 10 12 22 32 12]
