# Simple Arithmetic

In [8]:
import numpy as np

You could use arithmetic operators + - * / directly between NumPy arrays, but this section discusses an extension of the same where we have functions that can take any array-like objects e.g. lists, tuples etc. and perform arithmetic conditionally.

Arithmetic Conditionally: means that we can define conditions where the arithmetic operation should happen.

All of the discussed arithmetic functions take a where parameter in which we can specify that condition.

## Addition

The add() function sums the content of two arrays, the results in a new array.

In [9]:
# Add the values in arr1 to the values in arr2

arr1 = np.array([10,11,12,13,14,15])
arr2 = np.array([20,21,22,23,24,25])

narr1 = np.add(arr1,arr2)
print(narr1)

[30 32 34 36 38 40]


The example above will return [30 32 34 36 38 40] which is the sums of 10+20, 11+21, 12+22 etc.

## Subtraction

The subtract() function subtracts the values from one array with the values from another array, and retun the results in a new array

In [10]:
# Subtract the values in arr2 from the values in arr1
narr2 = np.subtract(arr1, arr2)
print(narr2)

[-10 -10 -10 -10 -10 -10]


## Multiplication

The multiply() function multiplies the values from one array with the values from another array, and return the results in a new array.

In [11]:
# Multiply the values in arr1 with the values in arr2

narr3 = np.multiply(arr1, arr2)
print(narr3)

[200 231 264 299 336 375]


## Division

The divide() function divides the values from one array with the values from another array, and return the results in a new array.

In [12]:
# Divide the values in arr1 with the values in arr2

narr4 = np.divide(arr1, arr2)
print(narr4)

[0.5        0.52380952 0.54545455 0.56521739 0.58333333 0.6       ]


## Power

The power() function rises the values from the first array to the power of the values of the second array, and return the results in a new array.

In [13]:
# Raise the valules in arr1 to the power of values in arr2

narr5 = np.power(arr1, arr2)
print(narr5)

[ 1661992960   602408795           0  1487897765  1090519040 -1144744561]


## Remainder

Both the mod() and the remainder() functions return the remainder of the values in the first array corresponding to the values in the second array, and return the results in a new array.

In [14]:
narr6 = np.mod(arr1, arr2)
print(narr6)

[10 11 12 13 14 15]


## Quotient and Mod

The divmod() function return both the quotient and the the mod. The return value is two arrays, the first array contains the quotient and second array contains the mod.

In [15]:
narr7 = np.divmod(arr1, arr2)
print(narr7)

(array([0, 0, 0, 0, 0, 0]), array([10, 11, 12, 13, 14, 15]))


## Absolute Values

Both the absolute() and the abs() functions do the same absolute operation element-wise but we should use absolute() to avoid confusion with python's inbuilt math.abs()

In [16]:
arr8 = np.array([-1, -3, 8, 0, 3, -4, 1, -2])
narr8 = np.absolute(arr8)
print(narr8)

[1 3 8 0 3 4 1 2]
