# NumPy Trigonometric Functions

In [1]:
import numpy as np

## Trigonometric Functions

NumPy provides the ufuncs sin(), cos() and tan() that take values in radians and produce the corresponding sin, cos and tan values.

In [2]:
# Find sine value of PI/2

s = np.sin(np.pi/2)
print(s)

1.0


In [3]:
# Find sine values for all of the values in an array

arr1 = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
s1 = np.sin(arr1)
print(s1)

[1.         0.8660254  0.70710678 0.58778525]


## Converts Degrees Into Radians

By default all of the trigonometric functions take radians as parameters but we can convert radians to degrees and vice versa as well in NumPy.

Note: radians values are pi/180 * degree_values.

In [6]:
# Convert all of the values in following array arr to radians 

arr2 = np.array([90, 180, 270, 360])
r2 = np.deg2rad(arr2)
print(r2)

[1.57079633 3.14159265 4.71238898 6.28318531]


## Radians to Degrees

In [7]:
# Concert all the values in following array arr to degrees

arr3 = np.array([np.pi/3, np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])
d3 = np.rad2deg(arr3)
print(d3)

[ 60.  90. 180. 270. 360.]


## Finding Angles

Finding angles from values of sine, cos, tan. E.g. sin, cos and tan inverse (arcsin, arccos, arctan).

NumPy provides ufuncs arcsin(), arccos() and arctan() that produce radian values for corresponding sin, cos and tan values given.

In [8]:
# Find the angle of 1.0
h = np.arcsin(1.0)
print(h)

1.5707963267948966


## Angles of Each Value in Arrays

In [10]:
# Find the angle for all of the sine values in the array

arr5 = np.array([1, -1, 0.1])
a5 = np.arcsin(arr5)
print(a5)

[ 1.57079633 -1.57079633  0.10016742]


## Hypotenues

Finding hypotenues using pythagoras theorem in NumPy.

NumPy provides the hypot() function that takes the base and perpendicular values and produces hypotenues based on pythagoras theorem.

In [11]:
# Find the hypotenues for 4 base and 3 perpendicular

base = 4
perpendicular = 3

hypotenues = np.hypot(base, perpendicular)
print(hypotenues)

5.0
